services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    command: >
      postgres
      -c max_connections=400
       -c timezone='Asia/Bangkok'
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8G"
        reservations:
          cpus: "2"
          memory: "500M"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "5000M"
        reservations:
          cpus: "2"
          memory: "5000M"
    environment:
      - TZ=UTC
    volumes:
      - ./ubuntu_data:/data
    tty: true
    stdin_open: true
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user@domain.com"
      - "PGADMIN_DEFAULT_PASSWORD=SuperSecret"

